siteTitle = "YoruNoHikage"
siteDescr = "I'm a lonesome programmer"
siteAuthorUsername = "YoruNoHikage"
siteAuthor = "Alexis Launay"
siteAuthorDescription = "Frenchy student @[ISENBrest](http://twitter.com/ISENBrest) working.
Web & Game #indie Dev who likes flying potatoes ! @[westindiecollective](http://westindiecollective.org) member.
日本語を勉強する。 Want to practise music !"

[social]
twitter = "http://twitter.com/YoruNoHikage"
github = "http://github.com/YoruNoHikage"
linkedin = "https://www.linkedin.com/in/alexislaunay"
youtube = "http://youtube.com/YoruNoHikage"
lastfm = "http://last.fm/user/YoruNoHikage"
steam = "http://steamcommunity.com/id/yorunohikage/"
email = "yorunohikage@gmail.com"

googleAnalyticsId = "UA-49971705-2"

linkPrefix = "/"
